### ISSUE TITLE
nettspend name capitalisation

### ISSUE THREAD

**Issue by 1skylars** [katelyynn/lotus#25]
**How should this be capitalised?**

nettspend should be capitalized as Nettspend

**Could you link the Last.fm page?**

https://www.last.fm/music/nettspend

**Do you have a source for this? (eg. Spotify)**

https://open.spotify.com/artist/2jl4qd6UbzeCmImT4nWbtA?si=DBT6EYnVT_6h8vRM5RZ1hg

**Comment by katelyynn** [comment]
confirmed ty
