### ISSUE TITLE
Willow > WILLOW

### ISSUE THREAD

**Issue by jabreen** [katelyynn/lotus#4]
**How should this be capitalised?**
WILLOW

**Could you link the Last.fm page?**
https://www.last.fm/music/Willow

**Do you have a source for this? (eg. Spotify)**
A source helps me verify this capitalisation is the most popular and should be applied. Enter one here.
https://open.spotify.com/artist/3rWZHrfrsPBxVy692yAIxF?si=v2aM10g0QGG2Blr5SL627Q

**Comment by katelyynn** [comment]
all applied :3 will show up in bleh/bwaa maximum of 4hr from now based on whenever it last downloaded

**Comment by katelyynn** [comment]
oh dont worry u can submit as many as u find and ill work thru in bulk usually
