### ISSUE TITLE
May It Never Falter - glaive (multiple tracks)

### ISSUE THREAD

**Issue by jabreen** [katelyynn/lotus#7]
**How should this be capitalised?**
For God and country -> For God and Country
Everydog has its day -> EVERYDOG HAS ITS DAY

**Could you link the Last.fm page?**
https://www.last.fm/music/glaive/may+it+never+falter
https://www.last.fm/music/glaive/may+it+never+falter/for+god+and+country
https://www.last.fm/music/glaive/may+it+never+falter/everydog+has+its+day

**Do you have a source for this? (eg. Spotify)**
A source helps me verify this capitalisation is the most popular and should be applied. Enter one here.
https://open.spotify.com/album/3tuFrjiGVuKMYiX7eY3s4P?si=Nzp0ls-MRK638vlCQScNDQ
https://open.spotify.com/track/5JmjXrRYZyJYmXz72IstSS?si=618ef40b7b4f41ed
https://open.spotify.com/track/3rLuup3EQbo8Tr6IBg0Dmc?si=89d718e3fba54f66

**Comment by katelyynn** [comment]
yeah he changed some capitalisation like a day after release or something n i forgot to actually fix it again oops

**Comment by jabreen** [comment]
lol all good !! im a metadata fiend so having the custom database in the theme makes it so much better

**Comment by katelyynn** [comment]
with u fully on that i wish lastfm were faster at fixing it but this is better than nothing

**Comment by jabreen** [comment]
for sure
