### ISSUE TITLE
CHROMAKOPIA - Tyler, The Creator (multiple tracks)

### ISSUE THREAD

**Issue by jabreen** [katelyynn/lotus#8]
**How should this be capitalised?**
CHROMAKOPIA
ST. CHROMA (feat. Daniel Caesar) -> St. Chroma (feat. Daniel Casear)
STICKY (feat. GloRilla, Sexyy Red & Lil Wayne) -> Sticky (feat. GloRilla, Sexyy Red & Lil Wayne)

also; Tyler, the Creator -> Tyler, The Creator

**Could you link the Last.fm page?**
https://www.last.fm/music/Tyler,+the+Creator/Chromakopia
https://www.last.fm/music/Tyler,+the+Creator/_/ST.+CHROMA+(feat.+Daniel+Caesar)
https://www.last.fm/music/Tyler,+the+Creator/_/STICKY+(feat.+GloRilla,+Sexyy+Red+&+Lil+Wayne)
https://www.last.fm/music/Tyler,+the+Creator

**Do you have a source for this? (eg. Spotify)**
A source helps me verify this capitalisation is the most popular and should be applied. Enter one here.
https://open.spotify.com/album/0U28P0QVB1QRxpqp5IHOlH
https://open.spotify.com/track/1QoyuMHNBe7lg3YW4Qtll4
https://open.spotify.com/track/3tFed7YsjGnIfxeLEQwx3R
https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF

**Comment by katelyynn** [comment]
it's a lil funny i've spoken to people about how tyler's name is capitalised wrong on last.fm but forgot to ever fix it

**Comment by katelyynn** [comment]
hesitating on changing the tyler name for now as "Tyler, the" is actually hardcoded into bleh to fix it splitting the comma into two artists, will do eventually thou

**Comment by katelyynn** [comment]
that issue has since been fixed in bleh as it accounts for both so i guess we'llsee what happens

**Comment by katelyynn** [comment]
closed in https://github.com/katelyynn/lotus/commit/42e6d9484a43758b2bb6d7494e243c200cd1b29c
